### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by cemo** [terraform-aws-modules/terraform-aws-appsync#28]
Hi all, we started to use [terraform-aws-appsync](https://github.com/terraform-aws-modules/terraform-aws-appsync) and we are happy to use it. I have just a minor issue about development on local boxes. How do you develop on AppSync? A simulator maybe? I have a few idea in my mind but before moving I wanted to ask here.

**Comment by svenlito** [comment]
@cemo Thanks for the issue. This blog post might be relevant for you https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/. It's a little opinionated towards AWS Amplify but I think you can derive what you need to do your local development.

**Comment by antonbabenko** [comment]
Good question! I remember that local development was not an issue for us when we were developing this module and using AppSync service at the same time because we deployed changes and used real AWS endpoints. It was rather easy to apply changes, wait 10 seconds and call the endpoint.

I'm interested to know what kind of local development experience would you want to have for AppSync&Terraform?
